#version: '3.8'

#POSTGRES DB
services:
  db:
    image: postgres:15
    container_name: postgress_db
    ports:
      - "5434:5432"
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

#REDIS DB
  #redis:
   # image: redis:latest
    #container_name: redis_db
    #ports:
      #- "6379:6379"
    #volumes:
     # - redis_data:/data


#FASTAPI
  api:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./mess:/app

#NGINX
  nginx:
    image: nginx:1.13.0
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    #depends_on:
     # - backend


volumes:
  postgres_data:
